/**
 * API router — Hono-based REST endpoints (adapted from Elysia)
 */

import { Hono } from "hono";
import { sessionsApi } from "./sessions.js";
import { feedApi } from "./feed.js";
import { teamsApi } from "./teams.js";
import { configApi } from "./config.js";
import { fleetApi } from "./fleet.js";
import { costsApi } from "./costs.js";
import { federationApi } from "./federation.js";
import { worktreesApi } from "./worktrees.js";
import { triggersApi } from "./triggers.js";
import { oracleApi } from "./oracle.js";
import { transportApi } from "./transport.js";
import { logsApi } from "./logs.js";
import { pulseApi } from "./pulse.js";
import { avengersApi } from "./avengers.js";
import { asksApi } from "./asks.js";
import { peerExecApi } from "./peer-exec.js";
import { proxyApi } from "./proxy.js";
import { uiStateApi } from "./ui-state.js";
import { tasksApi } from "./tasks.js";
import { inboxApi } from "./inbox-api.js";
import { workspaceApi } from "./workspace.js";
import { cronApi } from "./cron.js";
import { agentsApi } from "./agents.js";
import { wakeupApi } from "./wakeup.js";
import { taskLogsApi } from "./task-logs.js";
import { projectsApi } from "./projects.js";
import { loopsApi } from "./loops.js";
import { tokensApi } from "./tokens.js";
import { thinkApi } from "./think.js";
import { meetingsApi } from "./meetings.js";
import { chatLogApi } from "./chat-log.js";
import { hooksApi } from "./hooks.js";
import { commandsApi } from "./commands.js";
import { skillsApi } from "./skills.js";
import { vaultApi } from "./vault.js";
import { workflowsApi } from "./workflows.js";
import { oracleV2Api } from "./oracle-v2-bridge.js";
import { mailboxApi } from "./mailbox-api.js";
import { lineageApi } from "./lineage-api.js";
import { archiveApi } from "./archive-api.js";
import { swarmApi } from "./swarm-api.js";
import { fleetScanApi } from "./fleet-scan-api.js";
import { costModelApi } from "./cost-model-api.js";
import { standingOrdersApi } from "./standing-orders-api.js";
import { hybridSearchApi } from "./hybrid-search-api.js";
import { wireguardApi } from "./wireguard-api.js";
import { orchestratorApi } from "./orchestrator-api.js";

export const api = new Hono();

api.route("/", sessionsApi);
api.route("/", feedApi);
api.route("/", teamsApi);
api.route("/", configApi);
api.route("/", fleetApi);
api.route("/", costsApi);
api.route("/", federationApi);
api.route("/", worktreesApi);
api.route("/", triggersApi);
api.route("/", oracleApi);
api.route("/", transportApi);
api.route("/", logsApi);
api.route("/", pulseApi);
api.route("/", avengersApi);
api.route("/", asksApi);
api.route("/", peerExecApi);
api.route("/", proxyApi);
api.route("/", uiStateApi);
api.route("/", workspaceApi);
api.route("/", tasksApi);
api.route("/", inboxApi);
api.route("/", cronApi);
api.route("/", agentsApi);
api.route("/", wakeupApi);
api.route("/", taskLogsApi);
api.route("/", projectsApi);
api.route("/", loopsApi);
api.route("/", tokensApi);
api.route("/", thinkApi);
api.route("/", meetingsApi);
api.route("/", chatLogApi);
api.route("/", hooksApi);
api.route("/", commandsApi);
api.route("/", skillsApi);
api.route("/", vaultApi);
api.route("/", workflowsApi);
api.route("/", oracleV2Api);
api.route("/", mailboxApi);
api.route("/", lineageApi);
api.route("/", archiveApi);
api.route("/", swarmApi);
api.route("/", fleetScanApi);
api.route("/", costModelApi);
api.route("/", standingOrdersApi);
api.route("/", hybridSearchApi);
api.route("/", wireguardApi);
api.route("/", orchestratorApi);
